# Generated by Django 5.1.2 on 2025-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('website', models.URLField(blank=True, max_length=45, null=True)),
                ('cf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('piva', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
