# Generated by Django 5.1.2 on 2024-11-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id_account_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('website', models.URLField(blank=True, max_length=45, null=True)),
                ('cf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('piva', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pur_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('fk_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=45, unique=True)),
                ('fk_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.customer')),
                ('fk_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.state')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id_entry', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('fk_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id_line', models.AutoField(primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fk_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.account')),
                ('fk_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=45)),
                ('fk_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.account')),
                ('fk_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceP',
            fields=[
                ('id_invoice_p', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.account')),
                ('fk_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='erp.invoice')),
                ('fk_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fk_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.productcategory'),
        ),
    ]
