# Generated by Django 5.1.2 on 2025-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fk_customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
